### ISSUE TITLE
[Important] version 2.0.0

### ISSUE THREAD

**Issue by syguer** [zilkey/active_hash#145]
Main target
* [x] Drop old ruby support
  * [x] 1.9.3
  * [x] 2.1.x
  * [x] 2.2.x
  * [x] 2.3.x
* [x] Drop old Rails support
  * [x] 3.x
  * [x] 4.x
* Include breaking changes
  * [ ] https://github.com/zilkey/active_hash/pull/136

## TODO
* [x] Update document
  * [x] README
* [x] Keep code coverage

**Comment by kbrock** [comment]
The dropping of older ruby/rails version seems a bit aggressive but as long as we have branches to backport and release older gems, then we should be good.

**Comment by syguer** [comment]
@kbrock Yes, I agree.
ActiveRecord(and ActiveModel i.e. Rails!) is changing very aggressive so relating gem code  will be very complex if we keep compatibility on single branch.
So I'm going to separate backport branch. And of course I'll prepare documentation(ex. READNE.md)
.

**Comment by syguer** [comment]
I've branched! https://github.com/zilkey/active_hash/tree/stable-1.x

**Comment by kbrock** [comment]
Thanks for the branching. Oh and,

```diff
-This should be good.
+This should be great!
```

Supporting too many versions of `ActiveRecord` makes me nervous. I've seen the difficulty in jruby jdbc that was caused by a single version of the code supporting a wide range of versions.

Reducing the number of `ActiveRecord` versions supported will make the code base simpler.

On my team's project we needed to support the chaining of interfaces (e.g.: `where(:x => 1).where(:y => 2).order(:z)`) and have to say, the implementation is not so bad.
But it is becomes more complicated to also support legacy interface at the same time (e.g.: `find(:all, :conditions => {:x => 1, :y => 2}, :order => :z)`)

**Comment by syguer** [comment]
This project is aimed on release day of Ruby 2.5（probably 2017/12/25）

**Comment by danlesser** [comment]
This may be a really dumb thing to raise, especially on a closed issue, but I feel it's relevant. Your README currently reads as if version 2.x has been released. The closing of this issue indicates the same thing, yet the most recent release is 1.5.3. I'm honestly confused.

**Comment by syguer** [comment]
@danlesser Sorry for confuse 🙇 
You're right. I pushed v2.0.0 yesterday.
https://rubygems.org/gems/active_hash
